def get_desktop_success_html(deep_link_url: str) -> str:
    """Return HTML template for desktop authentication success page."""
    html_parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '    <meta charset="UTF-8">',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
        "    <title>Authentication Successful - Deckium</title>",
        "    <style>",
        "        body {",
        "            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;",
        "            display: flex;",
        "            justify-content: center;",
        "            align-items: center;",
        "            min-height: 100vh;",
        "            margin: 0;",
        "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);",
        "            color: white;",
        "        }",
        "        .container {",
        "            text-align: center;",
        "            background: rgba(255, 255, 255, 0.1);",
        "            padding: 40px;",
        "            border-radius: 16px;",
        "            backdrop-filter: blur(10px);",
        "            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);",
        "            max-width: 400px;",
        "        }",
        "        .success-icon {",
        "            font-size: 64px;",
        "            margin-bottom: 20px;",
        "        }",
        "        h1 {",
        "            margin: 0 0 16px 0;",
        "            font-size: 24px;",
        "            font-weight: 600;",
        "        }",
        "        p {",
        "            margin: 0 0 24px 0;",
        "            opacity: 0.9;",
        "            line-height: 1.5;",
        "        }",
        "        .spinner {",
        "            border: 3px solid rgba(255, 255, 255, 0.3);",
        "            border-top: 3px solid white;",
        "            border-radius: 50%;",
        "            width: 24px;",
        "            height: 24px;",
        "            animation: spin 1s linear infinite;",
        "            margin: 0 auto;",
        "        }",
        "        @keyframes spin {",
        "            0% { transform: rotate(0deg); }",
        "            100% { transform: rotate(360deg); }",
        "        }",
        "        .manual-link {",
        "            margin-top: 20px;",
        "            padding: 12px 24px;",
        "            background: rgba(255, 255, 255, 0.2);",
        "            border: 1px solid rgba(255, 255, 255, 0.3);",
        "            border-radius: 8px;",
        "            color: white;",
        "            text-decoration: none;",
        "            display: inline-block;",
        "            transition: all 0.2s;",
        "        }",
        "        .manual-link:hover {",
        "            background: rgba(255, 255, 255, 0.3);",
        "            transform: translateY(-1px);",
        "        }",
        "    </style>",
        "</head>",
        "<body>",
        '    <div class="container">',
        '        <div class="success-icon">✅</div>',
        "        <h1>Authentication Successful!</h1>",
        "        <p>Redirecting you back to Deckium...</p>",
        '        <div class="spinner"></div>',
        f'        <a href="{deep_link_url}" class="manual-link" id="manualLink" style="display: none;">',
        "            Open Deckium Manually",
        "        </a>",
        "    </div>",
        "",
        "    <script>",
        f'        const deepLinkUrl = "{deep_link_url}";',
        "        ",
        "        function redirectToApp() {",
        "            try {",
        "                window.location.href = deepLinkUrl;",
        "                ",
        "                setTimeout(() => {",
        "                    document.getElementById('manualLink').style.display = 'inline-block';",
        "                    document.querySelector('p').textContent = 'Click the button below if Deckium didn\\'t open automatically:';",
        "                    document.querySelector('.spinner').style.display = 'none';",
        "                }, 3000);",
        "                ",
        "                setTimeout(() => {",
        "                    window.close();",
        "                }, 5000);",
        "            } catch (error) {",
        "                console.error('Redirect failed:', error);",
        "                document.getElementById('manualLink').style.display = 'inline-block';",
        "                document.querySelector('p').textContent = 'Click the button below to open Deckium:';",
        "                document.querySelector('.spinner').style.display = 'none';",
        "            }",
        "        }",
        "",
        "        document.addEventListener('DOMContentLoaded', () => {",
        "            setTimeout(redirectToApp, 1000);",
        "        });",
        "        ",
        "        document.getElementById('manualLink').addEventListener('click', (e) => {",
        "            e.preventDefault();",
        "            window.location.href = deepLinkUrl;",
        "        });",
        "    </script>",
        "</body>",
        "</html>",
    ]

    return "\n".join(html_parts)
