name: Build and Deploy to Azure Blob Storage
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-multiplatform:
    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   platform: darwin
          #   shell: bash
          - os: windows-latest  
            platform: win32
            shell: bash
          - os: ubuntu-latest
            platform: linux
            shell: bash
    
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Type check
        working-directory: app
        run: npm run typecheck

      - name: Build application
        working-directory: app
        run: npm run package

      - name: Upload distributables to Azure Blob Storage
        run: |
          az storage blob upload-batch --destination 'releases' --destination-path '${{ matrix.platform }}' --source app/release/build --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --overwrite true 
